### ISSUE TITLE
Crush when calling stereoRectify. bug ?

### ISSUE THREAD

**Issue by arvisio** [bytedeco/javacv#1802]
Hello,
I get an **error** when calling **stereoRectify**:

I study works on dynamic projection.
In particular procamalib and procamtracker.

I received a calibration file through procamcalib and copied it into the procamtracker.
When I start tracking I get that error.

I also tried using the [camera-projector.yaml](https://github.com/natar-io/PapARt/blob/1.4-github/papart/data/calibration/camera-projector.yaml) from the [PapART](https://github.com/natar-io/PapARt) project, same bad result.

I found that the reason is in the **stereoRectify** call:
-MainFrame  trackingWorker.execute()
----TrackingWorker.doInBackground 
--------new ReflectanceInitializer
------------projectorDevice.getRectifyingHomography
-----------------stereoRectify      **< exception**

```
java.lang.RuntimeException: OpenCV(4.5.5) D:\a\javacpp-presets\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-4.5.5\modules\calib3d\src\undistort.dispatch.cpp:416: error: (-215:Assertion failed) CV_IS_MAT(_distCoeffs) && (_distCoeffs->rows == 1 || _distCoeffs->cols == 1) && (_distCoeffs->rows*_distCoeffs->cols == 4 || _distCoeffs->rows*_distCoeffs->cols == 5 || _distCoeffs->rows*_distCoeffs->cols == 8 || _distCoeffs->rows*_distCoeffs->cols == 12 || _distCoeffs->rows*_distCoeffs->cols == 14) in function 'cvUndistortPointsInternal'

	at org.bytedeco.opencv.global.opencv_calib3d.stereoRectify(Native Method)
```

Herethe code to reproduce the error:

```
        //left
        
        Mat camera_matrixL = new Mat(3, 3, CvType.CV_64FC1);
        
        DoubleIndexer srcIdx = camera_matrixL.createIndexer();
        srcIdx.put(0, 0, new double[]{
           725.3432277010294,   0.0,   331.91235060120476,
		   0.0,   728.0987748056441,   202.35866017353592,
		   0.0,   0.0,   1.0
        });                        
        
        CvMat distL = CvMat.create(1, 4, CvType.CV_64FC1);
        distL.put( 0.013108245708010578,   -0.09888522377388584,   -0.010077014999011482,   7.506298741617942E-4);
        
        
        //right
        Mat camera_matrixR = new Mat(3, 3, CvType.CV_64FC1);
        DoubleIndexer srcIdx2 = camera_matrixR.createIndexer();
        srcIdx2.put(0, 0, new double[]{
           1940.4781847943073,   0.0,   705.2767131913546,
		   0.0,   1746.0863675456435,   761.9744425794147,
		   0.0,   0.0,   1.0
        });
          
        CvMat distR = CvMat.create(1, 4, CvType.CV_64FC1);
        distR.put(0.0610552152371495,   -0.16205979414801663,   -0.0028666292947557306,   0.001669682933892569);
        
		
        Mat T = new Mat(3, 1, CvType.CV_64FC1);
        DoubleIndexer tValues = T.createIndexer();
        
        tValues.put(0, 0, new double[]{
           -72.9761951228808,
		   -2.1459919519516935,
		   -47.133400408948305
        });
                
        Mat R = new Mat(3, 3, CvType.CV_64FC1);
        DoubleIndexer rValues = R.createIndexer();
        
        rValues.put(0, 0, new double[]{
           0.998994700701929,   0.04283205403325078,   0.01322887435710044,
		   -0.03679788980716183,   0.9520563182488666,   -0.303701633496023,
		   -0.02560279819088608,   0.30290952779618113,   0.952675345904937
        });
        
        Mat R1 = new Mat(3, 3, CvType.CV_64FC1);
        Mat R2 = new Mat(3, 3, CvType.CV_64FC1);
        
        Mat P1 = new Mat(3, 4, CvType.CV_64FC1);
        Mat P2 = new Mat(3, 4, CvType.CV_64FC1);       

        stereoRectify(
                camera_matrixL, cvarrToMat(distL), 
                camera_matrixR, cvarrToMat(distR),
                new Size(320, 240), 
                R, T, 
                R1, R2, P1, P2, 
                new Mat(), 0, -1, new Size(), null, null);
```

I am expecting the result:

```
R1: 
[0.824128291367248, 0.2237730892907117, 0.5203250559769267;
 -0.1439411194838274, 0.9712321753526361, -0.1897077111809877;
 -0.5478079166001923, 0.08144732082197473, 0.8326300621771228]
R2: 
[0.8397677716164732, 0.0246948320114914, 0.542383863169091;
 -0.1047061660396974, 0.9875790002570115, 0.1171509156798576;
 -0.5327538911613602, -0.1551704982375387, 0.8319227175219726]
P1: 
[0, 0, 0, 0;
 0, 0, 0, 0;
 0, 0, 0, 0]
P2: 
[0, 0, 0, 0;
 0, 0, 0, 0;
 0, 0, 0, 0]
```

**Comment by saudet** [comment]
Could you try to set the "org.bytedeco.javacpp.nopointergc" system property
to "true" and see if that helps?

**Comment by arvisio** [comment]
Unfortunately, setting the [org.bytedeco.javacpp.noPointerGC](https://github.com/bytedeco/javacpp/wiki/System-Properties) variable did not help.

The variable was set as follows in netbeans:
Click on 'Re-run with different parameters' then in Maven Dialog add in properties 'org.bytedeco.javacpp.noPointerGC=true'.

Log:
`cd D:\procamtracker; "JAVA_HOME=C:\\Java\\jdk-13.0.2" cmd /c "\"C:\\netbeans\\java\\maven\\bin\\mvn.cmd\" -Dexec.vmArgs= \"-Dexec.args=${exec.vmArgs} -classpath %classpath ${exec.mainClass} ${exec.appArgs}\" \"-Dexec.executable=C:\\Java\\jdk-13.0.2\\bin\\java.exe\" -Dexec.mainClass=com.mycompany.checkerror.CheckError -Dexec.classpathScope=runtime **-Dorg.bytedeco.javacpp.noPointerGC=true** -Dexec.appArgs= -Dmaven.ext.class.path=C:\\netbeans\\java\\maven-nblib\\netbeans-eventspy.jar;C:\\netbeans\\java\\maven-nblib\\netbeans-cos.jar -Dfile.encoding=UTF-8 org.codehaus.mojo:exec-maven-plugin:3.0.0:exec"`

**Comment by saudet** [comment]
Your sample code above runs fine for me on both Linux and Windows.
Please also try with the snapshots: http://bytedeco.org/builds/
Maybe there's a recent bug that was fixed somewhere that affects only your machine.

**Comment by arvisio** [comment]
Hello,
Can you please see my steps for setting up the project

I really want the procamtracker to work.
[log.pdf](https://github.com/bytedeco/javacv/files/8505107/log.pdf)
[CheckError.txt](https://github.com/bytedeco/javacv/files/8505114/CheckError.txt)


I also tried to run on Java 1.8 - but it did not help solve the problem.
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

I'll try build JavaCV-platform and check the code there.

In any case, thanks for your attention to my problem.

**Comment by saudet** [comment]
Like I said, please try with the snapshots. It might be an issue that was fixed recently.

**Comment by arvisio** [comment]
Samuel, thanks for reply!

I have not worked with maven (pom.xml) before and have a trouble with understanding how to do the setup you wrote about.
I setup the project to use 1.5.8-snapshot (latest), but the function stereoRectify still does not work for me.
Please look at the detailed description of my steps, maybe I made a mistake somewhere.

[Build with snapshot.pdf](https://github.com/bytedeco/javacv/files/8511550/Build.with.snapshot.pdf)

**Comment by saudet** [comment]
That looks alright, so it looks like something about your machine is strange. You should try with another machine.

**Comment by arvisio** [comment]
I tryed on different PCs with Windows 10 :(
May be problem with Java version. I am using Oracle Java JDK-13.0.2.

Can you say which version of Java are you using ? And which version of Windows ?

**Comment by saudet** [comment]
Windows 10, with both JDK8 and JDK11, your sample code works fine.

**Comment by saudet** [comment]
To clarify, I copy/paste your code above https://github.com/bytedeco/javacv/issues/1802#issue-1205990526 in the main() method of a class and file named TestStereo.java, and then run this command, which executes without error:
```bash
java -cp /path/to/javacv-platform.jar TestStereo.java
```

**Comment by arvisio** [comment]
Sorry for the silence. I was busy with another task.

It's strange, I already raised the virtual machine, installed different versions of Java, ran the code - but it still throws an exception.

Can I ask you to make an archive with the JVM, javacv' jars and the calibration file so that I can test it on my machine and on the virtual machine ?

**Comment by saudet** [comment]
Ah, I see what the problem is. The order of the parameters for stereoRectify() is a bit different from cvStereoRectify(). I didn't notice that when I had to update the code to work with recent versions of OpenCV where cvStereoRectify() isn't available anymore. As you can see, not many people are testing this code, so thank you very much for reporting this issue! I pushed a fix in commit https://github.com/bytedeco/javacv/commit/d5943d73ac5bf6516d786f05f1ffad7f167da309. Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by arvisio** [comment]
Hi! 

Wow, it's working now!

It's funny - I wanted to dig deeper into what parameters were passed to the stereoRectify.
The code from the first comment, which worked, I typed manually, according to the openCV documentation :)

As always, the cause of many mistakes is inattention.

Thanks for the help.

Now I'll try the procamtracker on the projector.

And this issue has been resolved.

**Comment by saudet** [comment]
The fix has been released with JavaCV 1.5.8. Thanks for reporting!
